#ifndef DEF_MELON_KERNEL_CONFIG
#define DEF_MELON_KERNEL_CONFIG

#define OPT_DEBUG

//Color scheme
#define TXTLOGO_FGCOLOR 9
#define TXTLOGO_BGCOLOR 0
#define KVT_FGCOLOR 7
#define KVT_BGCOLOR 0
#define KVT_LIGHTCOLOR 6
#define KVT_ENTRYCOLOR 15

#define SHELL_FGCOLOR 0
#define SHELL_BGCOLOR 7

#endif
