#ifndef DEF_MELON_KERNEL_CONFIG
#define DEF_MELON_KERNEL_CONFIG

#define THIS_IS_MELON
#undef THIS_IS_NOT_MELON

#define OPT_DEBUG

//Color scheme
#define TXTLOGO_FGCOLOR 9
#define TXTLOGO_BGCOLOR 0
#define KVT_FGCOLOR 7
#define KVT_BGCOLOR 0
#define KVT_OKCOLOR 2
#define KVT_BLECOLOR 4	//BLE = Boot Log Entry
#define KVT_LIGHTCOLOR 8

#define SHELL_FGCOLOR 0
#define SHELL_BGCOLOR 7
#define SHELL_LIGHTCOLOR 8
#define SHELL_ENTRYCOLOR 6

#endif
